# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Todavía sin nombre
tagline:          Un sitio para colgar mis apuntes ...
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# dictionary of pages to show in my header
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/gristv/gristv.github.io
